# Generated by Django 5.2.5 on 2025-08-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Data de publicação'),
        ),
    ]
