# Generated by Django 5.2.5 on 2025-08-31 22:46

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_postpage_intro_postpagetag_postpage_tags'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='body',
            field=wagtail.fields.RichTextField(verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='postpage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='postpage',
            name='intro',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Introdução'),
        ),
    ]
